language: scala
scala:
  - 2.11.12
jdk: oraclejdk8

cache:
  directories:
    - $HOME/.sbt/boot
    - $HOME/.ivy2/cache

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean test;

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

notifications:
  email:
    - flatmap-squad@spotify.com
